import requests
import json
import datetime

links = {}

# 1. Node.js
try:
    node_res = requests.get('https://nodejs.org/dist/index.json').json()
    for node in node_res:
        if node['lts']:
            version = node['version']
            links['NodeJS'] = f"https://nodejs.org/dist/{version}/node-{version}-x64.msi"
            break
except Exception as e: print("Error Nodejs:", e)

# 2. Git for Windows
try:
    git_res = requests.get('https://api.github.com/repos/git-for-windows/git/releases/latest').json()
    for asset in git_res.get('assets', []):
        if '64-bit.exe' in asset['name']:
            links['Git'] = asset['browser_download_url']
            break
except Exception as e: print("Error Git:", e)

# 3. FFmpeg (Build BtbN)
try:
    ff_res = requests.get('https://api.github.com/repos/BtbN/FFmpeg-Builds/releases/latest').json()
    for asset in ff_res.get('assets', []):
        if 'win64-gpl' in asset['name'] and asset['name'].endswith('.zip'):
            links['FFmpeg'] = asset['browser_download_url']
            break
except Exception as e: print("Error FFmpeg:", e)

# 4. ImageMagick
try:
    img_res = requests.get('https://api.github.com/repos/ImageMagick/ImageMagick/releases/latest').json()
    for asset in img_res.get('assets', []):
        if 'Q16-HDRI-x64-dll.exe' in asset['name']:
            links['ImageMagick'] = asset['browser_download_url']
            break
except Exception as e: print("Error ImageMagick:", e)

# Simpan links.json
with open('links.json', 'w', encoding='utf-8') as f:
    json.dump(links, f, indent=4)

# ==========================================
# GENERATE README.MD OTOMATIS (Metode Anti-Error)
# ==========================================
timestamp = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
num_links = len(links)

# Buat tabel otomatis untuk daftar software
table_rows = ""
for name, url in links.items():
    table_rows += f"| {name} | [Download Link]({url}) |\n"

# Tulis README.md baris demi baris agar tidak ada masalah kutip tiga
with open('README.md', 'w', encoding='utf-8') as f:
    f.write("# 🤖 BAHAN BOT RDP (Auto Installer)\n\n")
    f.write("Repository ini berisi kumpulan link installer otomatis untuk persiapan *environment* Bot WhatsApp di RDP Windows.\n")
    f.write("Link di sini selalu diperbarui otomatis oleh sistem sehingga kamu selalu mendapat versi software terbaru!\n\n")
    
    f.write("## 📊 Statistik Repository\n")
    f.write(f"- 🕒 **Terakhir Diupdate:** {timestamp}\n")
    f.write(f"- 📦 **Jumlah Software Dilacak:** {num_links}\n")
    f.write("- ✅ **Status Link:** Aktif & Valid\n\n")
    
    f.write("### 📦 Daftar Software Otomatis\n")
    f.write("| Software | Link Download |\n")
    f.write("|---|---|\n")
    f.write(table_rows)
    f.write("\n---\n\n")
    
    f.write("## 🚀 Cara Install di RDP Windows (Sangat Mudah!)\n\n")
    f.write("Kamu tidak perlu lagi download file `.exe` satu-satu dari tabel di atas. Cukup ikuti 2 langkah ini:\n\n")
    
    f.write("### Langkah 1: Buka PowerShell sebagai Administrator\n")
    f.write("1. Klik tombol **Start** di Windows (atau tekan tombol Windows di keyboard).\n")
    f.write("2. Ketik **PowerShell**.\n")
    f.write("3. Klik kanan pada \"Windows PowerShell\" lalu pilih **Run as Administrator**.\n\n")
    
    f.write("### Langkah 2: Copy & Paste Script Ajaib ini\n")
    f.write("Salin kode di bawah ini, klik kanan di dalam jendela PowerShell untuk mem-paste, lalu tekan **Enter**:\n\n")
    f.write("```powershell\n")
    f.write("Set-ExecutionPolicy Bypass -Scope Process -Force; iwr -useb https://raw.githubusercontent.com/RusdiEneri/BAHANBOTRDP/main/install-bahan.ps1 | iex\n")
    f.write("```\n\n")
    
    f.write("### Langkah 3: Tinggal Ngopi ☕\n")
    f.write("Biarkan PowerShell bekerja. Script ini akan otomatis membaca tabel di atas, mengunduh semuanya langsung dari server resminya, dan menginstallnya secara *silent* (tanpa perlu ribet klik Next > Next).\n\n")
    f.write("Setelah selesai, RDP kamu siap digunakan untuk menjalankan Bot!\n\n")
    
    f.write("---\n\n")
    f.write("<details>\n")
    f.write("<summary><strong>🛠️ Untuk Developer (Cara Kerja Repo Ini)</strong></summary>\n")
    f.write("<br>\n")
    f.write("- `check_updates.py`: Script Python yang berjalan di GitHub Actions untuk mencari URL rilis terbaru dan secara otomatis membuat README.md ini.\n")
    f.write("- `links.json`: Database URL link terbaru.\n")
    f.write("- `install-bahan.ps1`: Script PowerShell yang membaca `links.json` dan mengeksekusi proses instalasi di mesin pengguna.\n")
    f.write("- `.github/workflows/update-links.yml`: Jadwal cron yang menjalankan script pencarian setiap hari.\n")
    f.write("</details>\n\n")
    
    f.write("---\n")
    f.write("Made with ❤️ by RusdiEneri | Auto-Generated by GitHub Actions\n")

print("Links & README.md updated successfully!")
